name: Test Java App with Gradle

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Build with Gradle
        run: ./gradlew build
        
      - name: Save Gradle cache
        env:
          GRADLE_USER_HOME: ${{ runner.temp }}/gradle
        run: echo "GRADLE_USER_HOME=${{ env.GRADLE_USER_HOME }}" >> $GITHUB_ENV
